# Site settings
title: Manideep Mamindlapally
general_email: manideepyx@ieee.org
academic_email: manideepyx@iitkgp.ac.in

description: > # this means to ignore newlines until "baseurl:"
  Give a brief description of yourself, and maybe your passion/interests. It is displayed in search results.

baseurl: "/" # the subpath of your site, e.g. /blog/

url: "https://manideepyx.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: 
linkedin_username: 
facebook_username: 
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html
twitter_username: manideepyx
gscholar_username: https://scholar.google.com/citations?hl=en&user=w-PmSxAAAAAJ

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
